#!/usr/bin/env python3
"""Embed a separately built, resident AArch64 EFI driver in BDS."""
import pathlib
import struct
import sys


def render(image):
    # Refuse an application: its callback would dangle after StartImage returns.
    if len(image) < 256 or len(image) > 32768 or image[:2] != b"MZ":
        raise ValueError("invalid or oversized BootKeyRelay image")
    pe = struct.unpack_from("<I", image, 0x3C)[0]
    if pe > len(image) - 96 or image[pe:pe + 4] != b"PE\0\0":
        raise ValueError("invalid PE header")
    machine = struct.unpack_from("<H", image, pe + 4)[0]
    magic = struct.unpack_from("<H", image, pe + 24)[0]
    subsystem = struct.unpack_from("<H", image, pe + 24 + 68)[0]
    if (machine, magic, subsystem) != (0xAA64, 0x20B, 11):
        raise ValueError("BootKeyRelay must be an AArch64 EFI boot-service driver")
    rows = ["  " + ", ".join(f"0x{byte:02x}" for byte in image[i:i + 16]) + ","
            for i in range(0, len(image), 16)]
    return ("/* Generated by embed_boot_key_relay.py; do not edit. */\n"
            "STATIC CONST UINT8 mBootKeyRelayImage[] = {\n"
            + "\n".join(rows) + "\n};\n")


if __name__ == "__main__":
    source, destination = map(pathlib.Path, sys.argv[1:])
    text = render(source.read_bytes())
    if not destination.exists() or destination.read_text() != text:
        temporary = destination.with_suffix(".tmp")
        temporary.write_text(text)
        temporary.replace(destination)
